---
- name: create main directory
  file:
    dest: /sami/etc/
    recurse: yes
    state: directory

- name: Insert config file
  template:
    src: application.properties.j2
    dest: /sami/etc/application.properties
    mode: 0755

- name: Insert docker-compose
  template:
    src: docker-compose.j2
    dest: /sami/etc/docker-compose.yml
    mode: 0755

- name: Install pip 
  apt:
    name:
      - python-pip
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Log into registry
  shell: "docker login {{ service_install_run_registry_url }} -u {{ service_install_run_registry_user }} -p {{ service_install_run_registry_password }}"

- name: run docker-compose
  shell: docker-compose -f /sami/etc/docker-compose.yml down

- name: run docker-compose
  shell: docker-compose -f /sami/etc/docker-compose.yml up -d

- name: wait for instance
  uri:
    url: "http://127.0.0.1:8090/"
    status_code: 404
  register: result
  until: result.status == 404
  retries: 120
  delay: 1

